# Generated by Django 5.2.14 on 2026-05-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
