# Generated by Django 5.2.14 on 2026-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
