# Generated by Django 5.2.14 on 2026-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoffer_availability_productoffer_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
