# Generated by Django 5.2.14 on 2026-05-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoffer_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='last_price',
        ),
    ]
