# Generated by Django 5.2.14 on 2026-05-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
