# Generated by Django 5.2.14 on 2026-05-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
