# Generated by Django 5.2.14 on 2026-05-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_url_remove_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
